import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { GameSetupProvider } from "@/context/game-setup-context";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='antialiased'>
      <body className='min-h-screen flex flex-col bg-gradient-to-b from-cyan-300 via-emerald-200 to-yellow-200'>
        <GameSetupProvider>
          <Navbar gems={0} />
          {children}
        </GameSetupProvider>
      </body>
    </html>
  );
}
