import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Press_Start_2P } from "next/font/google";
import { CurrencyProvider } from "@/context/currency-context";
import { GamePauseProvider } from "@/context/game-pause-context";
import { GameSetupProvider } from "@/context/game-setup-context";
import { NarrativeProvider } from "@/context/narrative-context";
import Navbar from "@/components/navbar";
import NarratorDialogueBox from "@/components/narrator/narrator-dialogue-box";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pressStart2P = Press_Start_2P({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-press-start-2p",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${geistSans.variable} ${geistMono.variable} ${pressStart2P.variable} antialiased`}>
      <body className='min-h-screen flex flex-col bg-linear-to-b from-cyan-300 via-emerald-200 to-yellow-200'>
        <GameSetupProvider>
          <CurrencyProvider>
            <GamePauseProvider>
              <NarrativeProvider>
                <Navbar />
                {children}
                <NarratorDialogueBox />
              </NarrativeProvider>
            </GamePauseProvider>
          </CurrencyProvider>
        </GameSetupProvider>
      </body>
    </html>
  );
}
